# Generated by Django 2.2.16 on 2022-02-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220203_0722'),
    ]

    operations = [
        migrations.RenameField(
            'comment',
            'created',
            'pub_date',
        )
    ]
